=== snext1220/stext/stext/common/sgml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="scenario">
    <xs:annotation>
      <xs:documentation>
        ルート要素（シナリオ全体を括る）
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="items">
          <xs:annotation>
            <xs:documentation>
              アイテム情報全体を括る要素
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="item">
                <xs:annotation>
                  <xs:documentation>
                    個々のアイテム情報。説明は15文字程度（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            アイテムコード（「i99」の形式。シナリオ内で一意であること）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="i[0-9]+" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="name" type="xs:string" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            アイテムの名前
                          </xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="itemKey">
            <xs:selector xpath="item" />
            <xs:field xpath="@id" />
          </xs:unique>
        </xs:element>
        <xs:element name="flags">
          <xs:annotation>
            <xs:documentation>
              フラグ情報全体を括る要素
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="flag">
                <xs:annotation>
                  <xs:documentation>
                    個々のフラグ情報。説明は15文字程度（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            フラグコード（「f99」の形式。シナリオ内で一意であること）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="f[0-9]+" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="flagKey">
            <xs:selector xpath="flag" />
            <xs:field xpath="@id" />
          </xs:unique>
        </xs:element>
        <xs:element name="enemies">
          <xs:annotation>
            <xs:documentation>
              モンスター／罠情報全体を括る要素
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="enemy">
                <xs:annotation>
                  <xs:documentation>
                    モンスター／罠の情報。説明は15文字程度（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            モンスター／罠コード（「m99」の形式。シナリオ内で一意であること）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="m[0-9]+" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="name" type="xs:string" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            敵／罠の名前（10文字程度）
                          </xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                      <xs:attribute name="element" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            属性（地・火・水・風・霊のいずれか）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="地" />
                            <xs:enumeration value="火" />
                            <xs:enumeration value="水" />
                            <xs:enumeration value="風" />
                            <xs:enumeration value="霊" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="attack" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            攻撃の種類（物理／魔法／毒／石化／凍結／呪い／忘却）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="物理" />
                            <xs:enumeration value="魔法" />
                            <xs:enumeration value="毒" />
                            <xs:enumeration value="石化" />
                            <xs:enumeration value="凍結" />
                            <xs:enumeration value="呪い" />
                            <xs:enumeration value="忘却" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="func" type="xs:string" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            ダメージ式（例：2L+R-STR。Lは左のサイコロ、Rは右のサイコロ）。 @attackが状態異常の時は回避条件（例：DEX>5、WIZARDなど）。カンマ区切りで複数指定も可（その場合はランダムに式を選択）
                          </xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="enemyKey">
            <xs:selector xpath="enemy" />
            <xs:field xpath="@id" />
          </xs:unique>
        </xs:element>
        <xs:element name="results">
          <xs:annotation>
            <xs:documentation>
              実績情報全体を括る要素
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="result">
                <xs:annotation>
                  <xs:documentation>
                    個々の実績情報。説明は15文字程度（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            実績コード（「r99」の形式。シナリオ内で一意であること）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="r[0-9]+" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="name" type="xs:string" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            実績の名前
                          </xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                      <xs:attribute name="level" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            実績レベル
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="[1-5]{1}" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="resultKey">
            <xs:selector xpath="result" />
            <xs:field xpath="@id" />
          </xs:unique>
        </xs:element>
        <xs:element name="licence">
          <xs:annotation>
            <xs:documentation>
              シナリオで利用している画像／楽曲のライセンス情報
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="work">
                <xs:annotation>
                  <xs:documentation>
                    作品情報（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        曲名（bgmの場合）、利用場所（pictureの場合。街、酒場など）
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="category" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        分類（bgm：音楽、picture：画像）
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="bgm" />
                        <xs:enumeration value="picture" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="creator" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        作者 or サイト名
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="url" type="xs:string" use="optional">
                    <xs:annotation>
                      <xs:documentation>
                        画像／楽曲の提供先（参照先）
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="scene">
          <xs:annotation>
            <xs:documentation>
              シーン情報（複数列挙可）。シナリオは、このシーン単位に表示されます。Markdown形式で記述してください。詳細は以下参照
              http://d.hatena.ne.jp/sorcerian/20171221
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:unsignedShort" use="required">
                  <xs:annotation>
                  <xs:documentation>
                     シーン番号（リンク時にも利用する番号なので一意で。スタートは0固定、プロローグであること）。あとで挿入に困らないよう、10、100単位で採番するのがお勧めです。
                  </xs:documentation>
                </xs:annotation>
                </xs:attribute>
                <xs:attribute name="flags" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      そのシーン移動時に立つフラグ（複数はカンマ区切り）
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="f[0-9]+[f0-9\,]*" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="enemies" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      そのシーンで登場する敵情報（複数はカンマ区切り）。敵情報は、ページ下部に表整形されます。
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="m[0-9]+[m0-9\,]*" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="items" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      そのシーン移動時に入手できるアイテム（複数はカンマ区切り。「-i～」でアイテム喪失）
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="(-)?i[0-9]+[\-i0-9\,]*" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="result" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      そのシーン移動時に取得できる実績
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="r[0-9]+" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="end" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      エンディングシーンか（happy：ハッピーエンド、bad：バッドエンド）。end属性でセーブデータも初期化されます。ハッピーエンド、バッドエンドいずれかで入手できるボーナスは変化。
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="happy" />
                      <xs:enumeration value="bad" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="allowMove" type="xs:boolean" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      番号指定による移動を許可するか（値はtrue固定）
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="se" type="xs:string" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      シーン移動時に再生する効果音（se.mp3であれば、「se」と指定）
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="bgm" type="xs:string" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      シーン移動時にBGMを切替（bgm_boss.mp3であれば、「boss」と指定。メインテーマbgm.mp3に戻す場合は、「main」と指定）
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="title" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation>
            シナリオタイトル
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="author" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation>
            作者名（ペンネームでも構いません）
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
    <xs:unique name="sceneKey">
      <xs:selector xpath="scene" />
      <xs:field xpath="@id" />
    </xs:unique>
  </xs:element>
</xs:schema>

=== snext1220/stext/stext/playground/scenario_empty_new.xml
<?xml version="1.0" encoding="utf-8"?>
<!--シナリオデータのルート要素 -->
<!--@title：シナリオのタイトル -->
<!--@author：著者名 -->
<!--@xmlns:xsi、@xsi:noNamespaceSchemaLocation：システム情報
    テンプレートの設定をそのまま利用してください。
    編集時の補助設定なので、実行時にはなくても問題ありません-->
<scenario title="シナリオタイトル" author="著者名"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.web-deli.com/sorcerian/next/stext/common/sgml.xsd">

  <!--シナリオの初期化情報 -->
  <init>

    <!--シナリオ起動時に生成される種族／性別／年齢を表す。
        すべてを許容する場合には指定しない -->
    <!--@race：種族（FIGHTER、WIZARD、DWARF、ELF）
        カンマ区切りで複数列記可 -->
    <!--@sex：性別（MALE、FEMALE）。複数列記は不可 -->
    <!--@age：年齢（YOUNG、ADULT、OLD）。カンマ区切りで複数列記可-->
	  <constraint race="FIGHTER,WIZARD" sex="FEMALE" age="YOUNG,ADULT"></constraint>

    <!--シナリオに適用するbgm（すべて既定ならば省略可） -->
    <!--@main：メインテーマ（既定はmain）-->
    <!--@happy：ハッピーエンド（既定はhappy）-->
    <!--@bad：バッドエンド（既定はbad）-->

    <!--命名のルール
        ・拡張子「.mp3」を除いたベース名で指定します（例えば、battle01.mp3ではなく、battle01）
        ・頭に「@」付きでシステム標準のBGMを意味します
        ・利用できる.mp3ファイルの名前については、STextページよりUtility 01を確認してください
        　（たとえば@field01、@castle01など）。
        ・標準BGMについては、シナリオフォルダーに.mp3ファイルを格納する必要はありません
        ・頭に「@」のないファイル名は、シナリオフォルダー配下の/bgmフォルダーを見に行きます。
        　対応する.mp3ファイルを準備してください。
        -->
		<bgm main="@field05" happy="@field04" bad="sigh"></bgm>
	</init>

  <!--アイテム情報-->
  <items>

    <!--個々のアイテム（複数列挙可） -->
    <!--@id：アイテムコード
    　　接頭辞は「i～」。シナリオ内で一意であること
        -->
    <!--@name：アイテムの名前 -->
    <!--#text：アイテムの説明（15文字程度）-->
    <item id="i01" name="こいし">何の変哲もない、石だ</item>
  </items>

  <!--フラグ情報 -->
  <flags>

    <!--個々のフラグ情報（複数列挙可）-->
    <!--@id：フラグコード
    　　接頭辞は「f～」。シナリオ内で一意であること-->
    <!--#text：フラグの表示名（15文字程度）。
        ステータス画面に粗筋替わりに表示されるので、できるだけ具体的な内容を。
    　　但し、先頭が「*」で始まるものは、ステータス画面で表示されない隠しフラグと見なす -->
    <flag id="f01">「☆」の道を調べた。</flag>
    <flag id="f02">*隠しフラグ</flag>
  </flags>

  <!--モンスター／罠情報-->
  <enemies>

    <!--敵／罠の情報 -->
    <!--@id：敵コード
        接頭辞「m～」。シナリオ内で一意であること -->
    <!--@name：敵／罠の名前（10文字程度）-->
    <!--@element：属性（敵のみ。地／火／水／風／霊）-->
    <!--@attack：攻撃の種類（物理／魔法／毒／石化／凍結／呪い／忘却から1つ）-->
    <!--@func：ダメージ式
        例：2L+R-STR。Lは左のサイコロ、Rは右のサイコロ
        @attackが状態異常の時は回避条件（例：DEX>5、WIZARDなど）
        カンマ区切りで複数指定も可（その場合はランダムに式を選択） -->
    <!--@drop：ドロップアイテム
        「mon/3」で「月×3」、「free1/50/50Gold」で「50Gold」
        無指定の場合は属性からドロップアイテムを確定 -->
    <!--#text：モンスターの説明（50文字程度）-->
    <enemy id="m01" name="人面岩" element="地" attack="物理"
      func="L-STR" drop="tue/3">喋るだけで、硬い岩だ。</enemy>
  </enemies>

  <!--実績情報-->
  <results>

    <!--個々の実績情報（複数列挙可）-->
    <!--@id　実績コード（接頭辞「r」。シナリオ内で一意であること） -->
    <!--@name　実績名（ex. ガジガジネズミ） -->
    <!--@level　難易度（1～5） -->
    <!--text　実績の成立条件（ex. 隧道でネズミに食い殺された） -->
    <result id="r01" name="冒険のはじまり" level="1">冒険を開始した</result>
</results>

<!--ライセンス情報-->
<licence>

  <!--作品情報（複数列挙可） -->
  <!--@name：曲名（bgmの場合）、利用場所（pictureの場合。街、酒場など） -->
  <!--@category：分類（bgm：音楽、picture：画像）-->
  <!--@creator：作者 or サイト名 -->
  <!--@url：参照先 -->
  <work name="ダンジョン" category="bgm" creator="Az"
    url="//venusaz.seesaa.net/"></work>
  <work name="グーラン" category="picture" creator="Falcom"
    url=""></work>
</licence>

<!--シナリオの各シーン-->
<scene id="0">
  プロローグ
</scene>
<!--
<scene id="100" items="-i01,i02" flags="f01,f02" enemies="m01,m02"
  end="happy" se="hoge" result="r01">
  本文
</scene>
<scene id="200" items="-i01,i02" flags="f01,f02" enemies="m01,m02"
  end="bad" se="hoge">
  本文
</scene>
-->
</scenario>

=== snext1220/stext/stext/material/scenario.xml
<?xml version="1.0" encoding="utf-8"?>
<scenario title="SText Data Book" author="著者名"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.web-deli.com/sorcerian/next/stext/common/sgml.xsd">

<!--初期化情報-->
<init>
  <bgm main="@field05" happy="@field04" bad="@town01" />
  <intro description="サンプルシナリオ紹介" />
</init>

<!--アイテム情報-->
<items>
</items>

<!--フラグ情報-->
<flags>
</flags>

<!--モンスター／罠情報-->
<enemies>
</enemies>

<!--実績情報-->
<results>
</results>

<!--ライセンス情報-->
<licence>
</licence>

<!--シナリオ本体-->
<scene id="0">
# SORCERIAN Text Data Book

プロトタイプ版です。

現時点では、緩い形での賛同（参加表明）があった方のシナリオのみを暫定的に入れていますが、もちろん、同じ要領で対応シナリオはどんどん増やしていければと。

フォーマットも最低限揃えていきたいとは思いますが、あまり無理をしても仕方がないので、様子を見つつ。
まずは、ご参考までに。

```
A long time ago,so long ago that memories did not exist.

Love was not wide spread among the people
and it was magic or might that ruled the lands.

There were men that set our on precarious adventures
in order to test their strength and courage.

People called these men.....


Sorcerian.
```

[新・消えた王様の杖](1000)
[災厄の夜 - テンペスト・ナイト](4000)
[少女は英雄を語りて](5000)
[その名はドラゴンスレイヤー](7000)
[魂の選択](10000)
[トラベラーズ☆イン](13000)
[終焉のゼロ - ドラゴンモード0 -](14000)
[常闇から来たる影](15000)
[金竜の陰謀](18000)
</scene>

<scene id="1000">
## 新・消えた王様の杖
</scene>

<scene id="4000">
## 災厄の夜 - テンペスト・ナイト
</scene>

<scene id="5000">
## 少女は英雄を語りて
</scene>

<scene id="7000">
## その名はドラゴンスレイヤー

シナリオ単位に、インデックスページを設けます。

モンスター以外を扱う場合には、以下のように見出しで区切ってください。
＃モンスターのみの場合は見出しは付けません。
もちろん、「舞台」「実績」など、ここで挙げた以外の見出しも可能です。

### モンスター

#### フィールド

[グリーンスライムLv1](1010)

#### 森林

#### ＊＊＊＊＊＊＊＊＊

### 登場人物

[ほげほげ](1010)

### アイテム

[ほげほげ](1010)
</scene>

<scene id="1010">
## グリーンスライムLv1

### 特性

…知能が無いためか緊張感無く街の近くに現れるスライム…
のどかさが増すだけだが一応倒しておくべきか。
趣味がスライムいじめとは言われない程度に。

%red%図などを加えるならば、ここで%/%

### 想定パラメータ

ここはドラスレ固有？他シナでの設置は難しいかも。

パラメーター ｜ 値
HP | 75
MP | 75
STR | 6
INT | 6
DEX | 7
KRM | 5
FREE1 | 0
FREE2 | 1

おそらく下に標準のenemy表示をする想定かと思われますが、現時点では割愛しています。
</scene>

<scene id="10000">
## 魂の選択
</scene>

<scene id="13000">
## トラベラーズ☆イン
</scene>

<scene id="14000">
## 終焉のゼロ - ドラゴンモード0 -
</scene>

<scene id="15000">
## 常闇から来たる影
</scene>

<scene id="18000">
## 金竜の陰謀
</scene>

<!--
<scene id="100" items="-i01,i02" flags="f01,f02" enemies="m01,m02"
  end="happy" se="hoge" result="r01">
  本文
</scene>
<scene id="200" items="-i01,i02" flags="f01,f02" enemies="m01,m02"
  end="bad" se="hoge">
  本文
</scene>
-->
</scenario>

=== snext1220/stext/stext/template/scenario.xml
<?xml version="1.0" encoding="utf-8"?>
<scenario title="シナリオタイトル" author="著者名"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.web-deli.com/sorcerian/next/stext/common/sgml.xsd">

<!--アイテム情報-->
<items>
  <item id="i88" name="アイテム名">アイテム説明</item>
  <item id="i99" name="アイテム名">アイテム説明</item>
</items>

<!--フラグ情報-->
<flags>
  <flag id="f88">フラグ説明</flag>
  <flag id="f99">フラグ説明</flag>
</flags>

<!--モンスター／罠情報-->
<enemies>
  <enemy id="m99" name="モンスター／罠名" element="地"
    attack="物理" func="式／回避条件">モンスター説明</enemy>
  <enemy id="m88" name="モンスター／罠名" element="火"
    attack="魔法" func="式／回避条件">モンスター説明</enemy>
  <enemy id="m77" name="モンスター／罠名" element="水"
    attack="毒" func="式／回避条件">モンスター説明</enemy>
  <enemy id="m66" name="モンスター／罠名" element="風"
    attack="凍結" func="式／回避条件">モンスター説明</enemy>
  <enemy id="m55" name="モンスター／罠名" element="霊"
    attack="石化" func="式／回避条件">モンスター説明</enemy>
  <enemy id="m44" name="モンスター／罠名" element="霊"
    attack="呪い" func="式／回避条件">モンスター説明</enemy>
  <enemy id="m33" name="モンスター／罠名" element="霊"
    attack="忘却" func="式／回避条件">モンスター説明</enemy>
</enemies>

<!--ライセンス情報-->
<licence>
	<work name="曲名" category="bgm" creator="作者名"
    url="作品アドレス"></work>
	<work name="画像名" category="picture" creator="作者名"
    url="作品アドレス"></work>
</licence>

<!--シナリオ本体-->
<scene id="0">
  プロローグ
</scene>
<scene id="100" items="-i01,i02" flags="f01,f02" enemies="m01,m02"
  end="happy" se="hoge" allowMove="true">
  本文
</scene>
<scene id="200" items="-i01,i02" flags="f01,f02" enemies="m01,m02"
  end="bad" se="hoge" allowMove="true">
  本文
</scene>
</scenario>

=== snext1220/stext/stext/playground/scenario_sample.xml
<?xml version="1.0" encoding="utf-8"?>
<scenario title="サンプルシナリオ" author="Rio"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.web-deli.com/sorcerian/next/stext/common/sgml.xsd">

<!--アイテム情報-->
<items>
  <item id="i99" name="アイテムA">えぇアイテムですわ</item>
</items>

<!--フラグ情報-->
<flags>
  <flag id="f99">物語が進みました。</flag>
</flags>

<!--モンスター／罠情報-->
<enemies>
  <enemy id="m99" name="キングドラゴン" element="霊"
    attack="物理" func="4L-STR">ドラゴン・オヴ・ドラゴン</enemy>
  <enemy id="m98" name="毒矢" element="地"
    attack="毒" func="DEX>2L">毒がたっぷりと塗られた矢</enemy>
</enemies>

<results>
<result id="r01" name="冒険のはじまり" level="1">
  冒険を開始した</result>
</results>

<!--ライセンス情報-->
<licence>
	<work name="メインテーマ" category="bgm" creator="Az"
    url="http://www.web-deli.com/sorcerian/next/stext.aspx"></work>
	<work name="挿絵A" category="picture" creator="Tokinoji"
    url="http://www.web-deli.com/sorcerian/next/gallery.aspx"></work>
</licence>

<!--シナリオ本体-->
<scene id="0">
ここにプロローグを書きます。

[次へ](100)
</scene>
<scene id="100" items="i99" flags="f99" enemies="m99,m98" result="r01">

- フラグf99が立ちます（=> ステータスから確認しましょう）
- アイテムi99を入手します（=> ステータスから確認しましょう）
- 敵としてm98、99が登場します（=> 下に情報が表示されます）

[敵に勝った](300)
[敵に負けた（バッドエンド）](200)
</scene>
<scene id="200" end="bad">
バッドエンディングです。
セーブデータは初期化されます。

(End)
</scene>
<scene id="300">
以下のボタンは、それぞれ条件を満たした場合にだけ表示されます。

魔法ボタンを有効にするには、あらかじめステータスから必要な星を追加します。

[フラグf99がある場合に表示](400 "f99")
[フラグf88がない場合に表示](400 "-f88")
[アイテムi99がある場合に表示](400 "i99")
[魔法HEALを使える場合に表示](400 "mHEAL")
</scene>
<scene id="400" end="happy">
ハッピーエンディングです。
セーブデータは初期化されます。

(End)
</scene>
</scenario>

=== snext1220/stext/stext/test/scenario.xml
<?xml version="1.0" encoding="utf-8"?>
<scenario title="チュートリアル" author="Rio"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.web-deli.com/sorcerian/next/stext/common/sgml.xsd">

<init>
  <bgm main="@field05" happy="@field04" bad="@town01" />
</init>

	<flags>
		<flag id="f01">「☆」の道を調べた。</flag>
		<flag id="f02">「〇」の道で、ジャイアントラットを倒した。</flag>
		<flag id="f03">「＊」の道で、怖い目を見た。</flag>
		<flag id="f04">*隠しフラグ</flag>
		<flag id="f05">*進行管理用の隠しフラグ</flag>
	</flags>

<scene id="0" flags="f02,f03,f04">
<![CDATA[
## ソーサリアン Textへようこそ！

ようこそ、ソーサリアン Textへ！
ようこそ、シナリオ開発の世界へ！

ここでは、まずシナリオ作成の基本のキ、
シーンについて理解します。

テスト](10 "f01&!(f02&f03&f04)"


[上手くいったら、次へ進みましょう](1)
[テスト](10 "f01&!(f02&f03&f04)")
[テスト2](11 "!f02&!f05")
]]>
</scene>

<scene id="1">
## シーンの移動

ゲームブックと言えば、シーン（パラグラフ）の移動。
シーンを移動しながら進んでいくのが、ゲームブック。

前のシーンでもボタンを押したら、シーンが切り替わりました。

プレイ画面の右上を見てみましょう。
確かに、「チュートリアル【1】」と書かれていますね。

### 移動ボタンを作成するには？

このような移動ボタンを作るには、以下のように表します。

```
[ボタンに表示するテキスト](移動先の番号)
```

たとえば、Scene 2に移動するボタンならば、こんな感じです。

```
[Scene 2に移動しよう！](2)
```

### やってみよう！ 

では、左のエディターエリアから自分で書いてみましょう。

編集するのは、下の部分です。
ボタンに表示するテキストは自由に変えて構いません！

---

！！ここを編集してみましょう！！

---

編集できたら、［シナリオを実行］ボタンをポチッとな。
そして、ボタンを押してシーン移動を確認してみましょう。
</scene>

<scene id="2">
## 物語のバックアップ

さて、Playgroundで編集した物語も、
そのままではページを切り替えた途端に消えてしまいます。

ここいらで一度、ファイルに保存しておきましょう。

左上に［ダウンロード］というボタンがあるので、こちらをぽちっと。

これでscenario.xmlという名前でPC上にファイルを保存できます。

### 実行可能な環境

あ、ダウンロード機能は最近のブラウザーだと、
大概大丈夫なはずですが、IE11はたぶん無理。
Chrome、Firefoxなどのブラウザーをご利用くださいね。

[いよいよチュートリアルも終盤です！](3)
</scene>

<scene id="3">
## 物語の分岐について

移動ボタンが作成できたら、
ソーサリアン Textでできることはぐんと広がります！

分岐するには、どうしたらいいかって？

カンタンです。
ボタンを複数用意すれば良いのです。

### やってみよう

ボタンはこんな感じで書くんでしたね。

```
[ボタンに表示するテキスト](移動先の番号)
```

ではでは、左のエディターエリアから
Scene 4、5へのリンクを作成してみましょう！

それぞれボタンテキストは
「ハッピーエンドへ」「バッドエンドへ」とします。

あ、例によって、編集するのは、下の部分ですよ？

---

！！ここを編集してみましょう！！
！！ここを編集してみましょう！！

---

え、むずかしい？

そんな人は、下の正解を写経してみましょうか。
写経も大切な練習です。

[ハッピーエンドへ](4)
[バッドエンドへ](5)
</scene>

<scene id="4" end="happy">
## ハッピーエンド

さてさて、最初のチュートリアルもこれでおしまい。

シナリオを終了するには、＜scene id="4" end="happy"＞
のように、「end="happy"」と付けてください。

これでボーナスアイテムが入手できたり、
すべてのデータが初期化されたりするので、
最後はend、
これお約束。

今回はハッピーエンドなので「end="happy"」ですが、
バッドエンドならば「end="bad"」です！

### 最後に

あ、下の［最初から冒険を開始する］ボタンを押してしまうと、
ページがリロードしてしまいます！

もし編集したデータを取っておきたいなら、
［ダウンロード］ボタンでファイルを保存しておきましょう♪

では、チュートリアル第2回でお会いしましょう～
</scene>

<scene id="5" end="bad">
## バッドエンド

さてさて、最初のチュートリアルもこれでおしまい。

シナリオを終了するには、＜scene id="5" end="bad"＞
のように、「end="bad"」と付けてください。

これでボーナスアイテムが入手できたり、
すべてのデータが初期化されたりするので、
最後はend、
これお約束。

今回はバッドエンドなので「end="bad"」ですが、
ハッピーエンドならば「end="happy"」です！

### 最後に

あ、下の［最初から冒険を開始する］ボタンを押してしまうと、
ページがリロードしてしまいます！

もし編集したデータを取っておきたいなら、
［ダウンロード］ボタンでファイルを保存しておきましょう♪

では、チュートリアル第2回でお会いしましょう～
</scene>

<scene id="10">
# Markdownについて

さあ、

シナリオデータを編集できたら、テキストの書き方についてちょっとだけ。

ソーサリアン Textのシナリオデータは、
Markdown（マークダウン）という記法で書かれています。

ブログなどでよく利用されている記法で、見出しや太字、箇条書きなど、
基本的な修飾を手軽に表現できます。

詳しくは、以下のようなぺージが役に立つんではなかろか。
https://qiita.com/tbpgr/items/989c6badefff69377da7






[other](10)
[happy](2)
[bad](3)
</scene>
</scenario>
