=== snext1220/stext/stext/common/sgml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="scenario">
    <xs:annotation>
      <xs:documentation>
        ルート要素（シナリオ全体を括る）
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="items">
          <xs:annotation>
            <xs:documentation>
              アイテム情報全体を括る要素
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="item">
                <xs:annotation>
                  <xs:documentation>
                    個々のアイテム情報。説明は15文字程度（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            アイテムコード（「i99」の形式。シナリオ内で一意であること）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="i[0-9]+" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="name" type="xs:string" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            アイテムの名前
                          </xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="itemKey">
            <xs:selector xpath="item" />
            <xs:field xpath="@id" />
          </xs:unique>
        </xs:element>
        <xs:element name="flags">
          <xs:annotation>
            <xs:documentation>
              フラグ情報全体を括る要素
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="flag">
                <xs:annotation>
                  <xs:documentation>
                    個々のフラグ情報。説明は15文字程度（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            フラグコード（「f99」の形式。シナリオ内で一意であること）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="f[0-9]+" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="flagKey">
            <xs:selector xpath="flag" />
            <xs:field xpath="@id" />
          </xs:unique>
        </xs:element>
        <xs:element name="enemies">
          <xs:annotation>
            <xs:documentation>
              モンスター／罠情報全体を括る要素
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="enemy">
                <xs:annotation>
                  <xs:documentation>
                    モンスター／罠の情報。説明は15文字程度（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            モンスター／罠コード（「m99」の形式。シナリオ内で一意であること）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="m[0-9]+" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="name" type="xs:string" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            敵／罠の名前（10文字程度）
                          </xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                      <xs:attribute name="element" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            属性（地・火・水・風・霊のいずれか）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="地" />
                            <xs:enumeration value="火" />
                            <xs:enumeration value="水" />
                            <xs:enumeration value="風" />
                            <xs:enumeration value="霊" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="attack" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            攻撃の種類（物理／魔法／毒／石化／凍結／呪い／忘却）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="物理" />
                            <xs:enumeration value="魔法" />
                            <xs:enumeration value="毒" />
                            <xs:enumeration value="石化" />
                            <xs:enumeration value="凍結" />
                            <xs:enumeration value="呪い" />
                            <xs:enumeration value="忘却" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="func" type="xs:string" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            ダメージ式（例：2L+R-STR。Lは左のサイコロ、Rは右のサイコロ）。 @attackが状態異常の時は回避条件（例：DEX>5、WIZARDなど）。カンマ区切りで複数指定も可（その場合はランダムに式を選択）
                          </xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="enemyKey">
            <xs:selector xpath="enemy" />
            <xs:field xpath="@id" />
          </xs:unique>
        </xs:element>
        <xs:element name="results">
          <xs:annotation>
            <xs:documentation>
              実績情報全体を括る要素
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="result">
                <xs:annotation>
                  <xs:documentation>
                    個々の実績情報。説明は15文字程度（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            実績コード（「r99」の形式。シナリオ内で一意であること）
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="r[0-9]+" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="name" type="xs:string" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            実績の名前
                          </xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                      <xs:attribute name="level" use="required">
                        <xs:annotation>
                          <xs:documentation>
                            実績レベル
                          </xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="[1-5]{1}" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="resultKey">
            <xs:selector xpath="result" />
            <xs:field xpath="@id" />
          </xs:unique>
        </xs:element>
        <xs:element name="licence">
          <xs:annotation>
            <xs:documentation>
              シナリオで利用している画像／楽曲のライセンス情報
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="work">
                <xs:annotation>
                  <xs:documentation>
                    作品情報（複数列挙可）
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        曲名（bgmの場合）、利用場所（pictureの場合。街、酒場など）
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="category" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        分類（bgm：音楽、picture：画像）
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="bgm" />
                        <xs:enumeration value="picture" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="creator" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        作者 or サイト名
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="url" type="xs:string" use="optional">
                    <xs:annotation>
                      <xs:documentation>
                        画像／楽曲の提供先（参照先）
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="scene">
          <xs:annotation>
            <xs:documentation>
              シーン情報（複数列挙可）。シナリオは、このシーン単位に表示されます。Markdown形式で記述してください。詳細は以下参照
              http://d.hatena.ne.jp/sorcerian/20171221
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:unsignedShort" use="required">
                  <xs:annotation>
                  <xs:documentation>
                     シーン番号（リンク時にも利用する番号なので一意で。スタートは0固定、プロローグであること）。あとで挿入に困らないよう、10、100単位で採番するのがお勧めです。
                  </xs:documentation>
                </xs:annotation>
                </xs:attribute>
                <xs:attribute name="flags" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      そのシーン移動時に立つフラグ（複数はカンマ区切り）
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="f[0-9]+[f0-9\,]*" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="enemies" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      そのシーンで登場する敵情報（複数はカンマ区切り）。敵情報は、ページ下部に表整形されます。
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="m[0-9]+[m0-9\,]*" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="items" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      そのシーン移動時に入手できるアイテム（複数はカンマ区切り。「-i～」でアイテム喪失）
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="(-)?i[0-9]+[\-i0-9\,]*" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="result" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      そのシーン移動時に取得できる実績
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="r[0-9]+" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="end" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      エンディングシーンか（happy：ハッピーエンド、bad：バッドエンド）。end属性でセーブデータも初期化されます。ハッピーエンド、バッドエンドいずれかで入手できるボーナスは変化。
                    </xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="happy" />
                      <xs:enumeration value="bad" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="allowMove" type="xs:boolean" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      番号指定による移動を許可するか（値はtrue固定）
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="se" type="xs:string" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      シーン移動時に再生する効果音（se.mp3であれば、「se」と指定）
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="bgm" type="xs:string" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      シーン移動時にBGMを切替（bgm_boss.mp3であれば、「boss」と指定。メインテーマbgm.mp3に戻す場合は、「main」と指定）
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="title" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation>
            シナリオタイトル
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="author" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation>
            作者名（ペンネームでも構いません）
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
    <xs:unique name="sceneKey">
      <xs:selector xpath="scene" />
      <xs:field xpath="@id" />
    </xs:unique>
  </xs:element>
</xs:schema>

=== snext1220/stext/stext/playground/tutorial1.xml
<?xml version="1.0" encoding="utf-8"?>
<scenario title="チュートリアル" author="Rio"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.web-deli.com/sorcerian/next/stext/common/sgml.xsd">

<init>
  <bgm main="@field05" happy="@field04" bad="@town01" />
</init>

<scene id="0">
## ソーサリアン Textへようこそ！

ようこそ、ソーサリアン Textへ！
ようこそ、シナリオ開発の世界へ！

ここでは、まずシナリオ作成の基本のキ、
シーンについて理解します。

### シーンとは！？

まずは、これが基本。

+ ソーサリアン Textでは、パラグラフのことを**シーン**と呼びます。
+ ひとつのシーンは＜scene＞～＜/scene＞ で表します。
+ 最初のシーンは、＜scene id="0"＞～＜/scene＞の間に書きます。

「id="0"」というのは、シーン（パラグラフ）番号です。

### Scene 0は特別なシーン

＜scene id="0"＞～＜/scene＞は、0番目のシーン、Scene 0です。
ゲームを開始すると、まず最初に表示されます。

今表示されているのも、じつはScene 0です。
ページの右上にも「チュートリアル【0】」と書かれています。
【0】は、現在表示されているシーン番号です。

Scene 0には、普通、**プロローグ、冒険の目的**などを書いていきます。

### 早速、練習

では早速、左のエディターエリアから、

---

！！このあたり！！

---

を、適当に編集してみましょう！

ホントは、＜scene id="0"＞～＜/scene＞の中であれば、
どこでも編集できるんですが、説明が消えてしまうのは不便だと思うので。

まずは、ここだけで我慢、がまん...

### 修正したシナリオを確認

修正できたら、［シナリオを実行］ボタンをクリックします。

「続きから開始しますか？」と聞かれたら、
［続きから］ボタンをクリックしましょう！

さあ、編集した内容が反映されましたか？

されましたね。
されたに違いありません！


[上手くいったら、次へ進みましょう](1)
</scene>

<scene id="1">
## シーンの移動

ゲームブックと言えば、シーン（パラグラフ）の移動。
シーンを移動しながら進んでいくのが、ゲームブック。

前のシーンでもボタンを押したら、シーンが切り替わりました。

プレイ画面の右上を見てみましょう。
確かに、「チュートリアル【1】」と書かれていますね。

### 移動ボタンを作成するには？

このような移動ボタンを作るには、以下のように表します。

```
[ボタンに表示するテキスト](移動先の番号)
```

たとえば、Scene 2に移動するボタンならば、こんな感じです。

```
[Scene 2に移動しよう！](2)
```

### やってみよう！ 

では、左のエディターエリアから自分で書いてみましょう。

編集するのは、下の部分です。
ボタンに表示するテキストは自由に変えて構いません！

---

！！ここを編集してみましょう！！

---

編集できたら、［シナリオを実行］ボタンをポチッとな。
そして、ボタンを押してシーン移動を確認してみましょう。
</scene>

<scene id="2">
## 物語のバックアップ

さて、Playgroundで編集した物語も、
そのままではページを切り替えた途端に消えてしまいます。

ここいらで一度、ファイルに保存しておきましょう。

左上に［ダウンロード］というボタンがあるので、こちらをぽちっと。

これでscenario.xmlという名前でPC上にファイルを保存できます。

### 実行可能な環境

あ、ダウンロード機能は最近のブラウザーだと、
大概大丈夫なはずですが、IE11はたぶん無理。
Chrome、Firefoxなどのブラウザーをご利用くださいね。

[いよいよチュートリアルも終盤です！](3)
</scene>

<scene id="3">
## 物語の分岐について

移動ボタンが作成できたら、
ソーサリアン Textでできることはぐんと広がります！

分岐するには、どうしたらいいかって？

カンタンです。
ボタンを複数用意すれば良いのです。

### やってみよう

ボタンはこんな感じで書くんでしたね。

```
[ボタンに表示するテキスト](移動先の番号)
```

ではでは、左のエディターエリアから
Scene 4、5へのリンクを作成してみましょう！

それぞれボタンテキストは
「ハッピーエンドへ」「バッドエンドへ」とします。

あ、例によって、編集するのは、下の部分ですよ？

---

！！ここを編集してみましょう！！
！！ここを編集してみましょう！！

---

え、むずかしい？

そんな人は、下の正解を写経してみましょうか。
写経も大切な練習です。

[ハッピーエンドへ](4)
[バッドエンドへ](5)
</scene>

<scene id="4" end="happy">
## ハッピーエンド

さてさて、最初のチュートリアルもこれでおしまい。

シナリオを終了するには、＜scene id="4" end="happy"＞
のように、「end="happy"」と付けてください。

これでボーナスアイテムが入手できたり、
すべてのデータが初期化されたりするので、
最後はend、
これお約束。

今回はハッピーエンドなので「end="happy"」ですが、
バッドエンドならば「end="bad"」です！

### 最後に

あ、下の［最初から冒険を開始する］ボタンを押してしまうと、
ページがリロードしてしまいます！

もし編集したデータを取っておきたいなら、
［ダウンロード］ボタンでファイルを保存しておきましょう♪

では、チュートリアル第2回でお会いしましょう～
</scene>

<scene id="5" end="bad">
## バッドエンド

さてさて、最初のチュートリアルもこれでおしまい。

シナリオを終了するには、＜scene id="5" end="bad"＞
のように、「end="bad"」と付けてください。

これでボーナスアイテムが入手できたり、
すべてのデータが初期化されたりするので、
最後はend、
これお約束。

今回はバッドエンドなので「end="bad"」ですが、
ハッピーエンドならば「end="happy"」です！

### 最後に

あ、下の［最初から冒険を開始する］ボタンを押してしまうと、
ページがリロードしてしまいます！

もし編集したデータを取っておきたいなら、
［ダウンロード］ボタンでファイルを保存しておきましょう♪

では、チュートリアル第2回でお会いしましょう～
</scene>

<scene id="10">
# Markdownについて

さあ、

シナリオデータを編集できたら、テキストの書き方についてちょっとだけ。

ソーサリアン Textのシナリオデータは、
Markdown（マークダウン）という記法で書かれています。

ブログなどでよく利用されている記法で、見出しや太字、箇条書きなど、
基本的な修飾を手軽に表現できます。

詳しくは、以下のようなぺージが役に立つんではなかろか。
https://qiita.com/tbpgr/items/989c6badefff69377da7






[other](10)
[happy](2)
[bad](3)
</scene>
</scenario>
